[build]
  # Build command - uses your existing working build script
  command = "npm run build:client"
  
  # Directory to publish - where Vite outputs the built files
  publish = "dist/public"
  
  # Node.js version and environment variables
  [build.environment]
    NODE_VERSION = "18"
    VITE_SUPABASE_URL = "https://jxrkgdqhynesvdnbhgzu.supabase.co"
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cmtnZHFoeW5lc3ZkbmJoZ3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzIzNzksImV4cCI6MjA3MTY0ODM3OX0.fSCXA1ZpIOswUPmdhn3O0wh7iIKtcxkZTlMiHlDHCCs"

# API redirects to Netlify Functions (must come before SPA redirect)
[[redirects]]
  from = "/api/auth/user"
  to = "/.netlify/functions/auth-user"
  status = 200

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200

# SPA routing - redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
